item: "Lightly played Alakazam Holofoil Pokemon Card, valued at $28.25 on TCGPlayer"
starting_price: 0
price_increment: 1
log_file: "common_auction_log_gemini.csv"
max_rounds: 200 # Not implemented in English

seller:
  attributes:
    bidding_knowledge: "sophiscated"
    urgency_to_sell: "medium"

buyers:
  - attributes:
      risk_tolerance: "medium"
      bidding_knowledge: "sophiscated"
      rational_bidder: true
    budget: 40
  - attributes:
      risk_tolerance: "medium"
      bidding_knowledge: "sophiscated"
      rational_bidder: true
    budget: 40
  - attributes:
      risk_tolerance: "medium"
      bidding_knowledge: "sophiscated"
      rational_bidder: true
    budget: 40
  - attributes:
      risk_tolerance: "medium"
      bidding_knowledge: "sophiscated"
      rational_bidder: true
    budget: 40
  - attributes:
      risk_tolerance: "medium"
      bidding_knowledge: "sophiscated"
      rational_bidder: true
    budget: 40
  - attributes:
      risk_tolerance: "medium"
      bidding_knowledge: "sophiscated"
      rational_bidder: true
    budget: 40
  - attributes:
      risk_tolerance: "medium"
      bidding_knowledge: "sophiscated"
      rational_bidder: true
    budget: 40
  - attributes:
      risk_tolerance: "low"
      bidding_knowledge: "sophiscated"
      rational_bidder: true
    budget: 40
  - attributes:
      risk_tolerance: "low"
      bidding_knowledge: "sophiscated"
      rational_bidder: true
    budget: 40
  - attributes:
      risk_tolerance: "low"
      bidding_knowledge: "sophiscated"
      rational_bidder: true
    budget: 40

auctioneer_attributes:
  experience: "veteran"
  style: "energetic"
