#item: "Valuable Painting"
#starting_price: 100
#price_increment: 10
#log_file: "auction_log.csv"

item: "Valuable Painting"
starting_price: 600
price_decrement: 10
log_file: "dutch_auction_log.csv"
max_rounds: 100 # Not implemented in English

seller:
  attributes:
    art_knowledge: "expert"
    urgency_to_sell: "medium"

buyers:
  - attributes:
      risk_tolerance: "high"
      art_knowledge: "expert"
    budget: 500
  - attributes:
      risk_tolerance: "medium"
      art_knowledge: "novice"
    budget: 300
  - attributes:
      risk_tolerance: "low"
      art_knowledge: "intermediate"
    budget: 400

auctioneer_attributes:
  experience: "veteran"
  style: "energetic"
