item: "Lightly played Charizard Pokemon Go Card, valued at $1200 on TCGPlayer"
starting_price: 2000
price_decrement: 100
log_file: "dutch_auction_log.csv"
max_rounds: 100 # Not implemented in English

seller:
  attributes:
    bidding_knowledge: "sophiscated"
    urgency_to_sell: "medium"

buyers:
  - attributes:
      risk_tolerance: "medium"
      bidding_knowledge: "sophiscated"
      rational_bidder: true
    budget: 2000
  - attributes:
      risk_tolerance: "medium"
      bidding_knowledge: "sophiscated"
      rational_bidder: true
    budget: 2000
  - attributes:
      risk_tolerance: "medium"
      bidding_knowledge: "sophiscated"
      rational_bidder: true
    budget: 2000
  - attributes:
      risk_tolerance: "medium"
      bidding_knowledge: "sophiscated"
      rational_bidder: true
    budget: 2000
  - attributes:
      risk_tolerance: "medium"
      bidding_knowledge: "sophiscated"
      rational_bidder: true
    budget: 2000
  - attributes:
      risk_tolerance: "medium"
      bidding_knowledge: "sophiscated"
      rational_bidder: true
    budget: 2000
  - attributes:
      risk_tolerance: "medium"
      bidding_knowledge: "sophiscated"
      rational_bidder: true
    budget: 2000
  - attributes:
      risk_tolerance: "low"
      bidding_knowledge: "sophiscated"
      rational_bidder: true
    budget: 2000
  - attributes:
      risk_tolerance: "low"
      bidding_knowledge: "sophiscated"
      rational_bidder: true
    budget: 2000
  - attributes:
      risk_tolerance: "low"
      bidding_knowledge: "sophiscated"
      rational_bidder: true
    budget: 2000

auctioneer_attributes:
  experience: "veteran"
  style: "energetic"
