item: "Lightly played Alakazam Holofoil Pokemon Card, valued at $28.25 on TCGPlayer"
starting_price: 42
price_decrement: 1
log_file: "dutch_auction_log_geminiflash.csv"
max_rounds: 200 # Not implemented in English

auctioneer:
  attributes:
    bidding_knowledge: "sophiscated"
    urgency_to_sell: "medium"

buyers:
  - attributes:
      bidding_knowledge: "sophiscated"
      rational_bidder: true
    budget: 30
  - attributes:
      bidding_knowledge: "sophiscated"
      rational_bidder: true
    budget: 32
  - attributes:
      bidding_knowledge: "sophiscated"
      rational_bidder: true
    budget: 34
  - attributes:
      bidding_knowledge: "sophiscated"
      rational_bidder: true
    budget: 35
  - attributes:
      bidding_knowledge: "sophiscated"
      rational_bidder: true
    budget: 35
  - attributes:
      bidding_knowledge: "sophiscated"
      rational_bidder: true
    budget: 36
  - attributes:
      bidding_knowledge: "sophiscated"
      rational_bidder: true
    budget: 37
  - attributes:
      bidding_knowledge: "sophiscated"
      rational_bidder: true
    budget: 38
  - attributes:
      bidding_knowledge: "sophiscated"
      rational_bidder: true
    budget: 39
  - attributes:
      bidding_knowledge: "sophiscated"
      rational_bidder: true
    budget: 40

auctioneer_attributes:
  experience: "veteran"
  style: "energetic"
